### ISSUE TITLE
How exactly do the icons work?

### ISSUE THREAD

**Issue by CombatVolcano** [ChrisKnott/Eel#140]
I'm working in a Windows 10 environment and packaging multiple apps for users.

I'm having problems with the incorrect icon appearing. I feel like I'd first like to know how to specify the icon filename? If I could use unique file names this problem would likely disappear.

To clarify, I am getting an app icon from pyinstaller no problem, but the Eel browser window has the wrong icon, one from a different app which also used favicon.ico

**Comment by ChrisKnott** [comment]
This must be a caching issue, it should be fixed with the latest version.
It gets the icon in the same way as a webpage (by making a request to `http://localhost:8000/favicon.ico` or whatever)

**Comment by weathon** [comment]
@ChrisKnott I add the icon to my html file folder and I also try to clean the cache, but it still doesn't work
